apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: windows
spec:
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  namespace: default
  name: windows
subsets:
  - addresses:
      - ip: 10.1.0.1
    ports:
      - port: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cls
  namespace: default
  annotations:
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
    - hosts:
        - cardifftec.uk
        - db.cardifftec.uk
        - spacearcaders.co.uk
      secretName: cls-tls
  rules:
  - host: cardifftec.uk
    http: &http
      paths:
      - path: /
        backend:
          serviceName: windows
          servicePort: 80
  - host: db.cardifftec.uk
    http: *http
  - host: spacearcaders.co.uk
    http: *http