apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: chatbot-staging
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      volumes:
        - name: dialogflow-secret
          secret:
            secretName: dialogflow-secret
        - name: gpay-keys
          secret:
            secretName: gpay-keys
      containers:
        - name: django-gunicorn
          image: theenbyperor/wewillfixyourpcbot_django:latest
          imagePullPolicy: Always
          command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:80", "--forwarded-allow-ips", "*", "--access-logfile", "-", "wewillfixyourpc_bot.wsgi:application"]
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/dialogflow-secret/"
              name: dialogflow-secret
              readOnly: true
            - mountPath: "/gpay-keys/"
              name: gpay-keys
              readOnly: true
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: wewillfixyourpc_bot.settings
            - name: EXTERNAL_URL
              value: "https://staging.bot.cardifftec.uk/"
            - name: CELERY_RESULT_BACKEND
              value: "redis://redis"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: db-host
                  name: db-conf
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: db-name
                  name: db-conf
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: db-user
                  name: db-creds
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: db-pass
                  name: db-creds
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  key: url
                  name: rabbitmq-user
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret-key
                  name: django-secret
            - name: PUSH_PRIV_KEY
              valueFrom:
                secretKeyRef:
                  key: push-priv-key
                  name: webpush-secrets
            - name: WORLDPAY_TEST_KEY
              valueFrom:
                secretKeyRef:
                  key: test-key
                  name: worldpay-keys
            - name: WORLDPAY_LIVE_KEY
              valueFrom:
                secretKeyRef:
                  key: live-key
                  name: worldpay-keys
            - name: FACEBOOK_VERIFY_TOKEN
              valueFrom:
                secretKeyRef:
                  key: verify-token
                  name: facebook-secrets
            - name: FACEBOOK_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: access-token
                  name: facebook-secrets
            - name: TWITTER_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  key: consumer-key
                  name: twitter-secrets
            - name: TWITTER_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  key: consumer-secret
                  name: twitter-secrets
            - name: TWITTER_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: access-token
                  name: twitter-secrets
            - name: TWITTER_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  key: access-token-secret
                  name: twitter-secrets