apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa
  namespace: chatbot
  labels:
    app: rasa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa
  template:
    metadata:
      labels:
        app: rasa
    spec:
      volumes:
        - name: secrets
          secret:
            secretName: rasa-secrets
      containers:
        - name: rasa
          image: theenbyperor/rasa@sha256:26a64302765d952f7d0dd7e2834d16ad8b829c12b36cf158d17f928e749fe099
          imagePullPolicy: Always
          args: ["run", "--endpoints", "/secrets/endpoints.yml", "--credentials", "/secrets/credentials.yml", "-v"]
          ports:
            - containerPort: 5005
          volumeMounts:
            - name: secrets
              mountPath: "/secrets"
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  namespace: chatbot
  name: rasa
  labels:
    app: rasa
spec:
  selector:
    app: rasa
  ports:
    - port: 5005
      targetPort: 5005
      name: nginx