apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: keycloak
data:
  DB_VENDOR: postgres
  DB_ADDR: postgres.postgres
  DB_DATABASE: keycloak
  DB_USER: keycloak
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: jboss/keycloak
          args: ["-Dkeycloak.profile=preview"]
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: keycloak-config
            - secretRef:
                name: db-pass
          env:
            - name: PROXY_ADDRESS_FORWARDING
              value: "True"
---
apiVersion: v1
kind: Service
metadata:
  namespace: keycloak
  name: keycloak
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: keycloak
  annotations:
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
    - hosts:
        - account.cardifftec.uk
      secretName: keycloak-tls
  rules:
  - host: account.cardifftec.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: keycloak
          servicePort: 80
